local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Swiss Knief PRX by WeepingAngel", "BloodTheme")

local Main = Window:NewTab("Universal")
local MainSection = Main:NewSection("Universal")

MainSection:NewButton("Toggle ESP", "Toggle ESP, Stream Proof for obs (Synapse X Needed!)", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Crafttino21/universal-esp/main/PRX%20ESP.lua'))()
end)
MainSection:NewButton("Toggle Aimbot", "Snaps your mouse to other players head", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/WRD%20Aimbot.txt"))()
end)
MainSection:NewButton("Teleport to Player", "a simple Teleporter to a player", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Teleport%20To%20Player.txt"))()
end)
MainSection:NewButton("Toggle Fly", "Why walk when you can fly :)", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Fly.txt"))()
end)


local Script = Window:NewTab("Script Hub")
local ScriptSection = Script:NewSection("Script Hub")

ScriptSection:NewButton("OwlHub", "a Good Multi Game Multi Exploit xD", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/CriShoux/OwlHub/master/OwlHub.txt"))()
end)
ScriptSection:NewButton("DarkHub v4", "Its simple, its DarkHub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RandomAdamYT/DarkHub/master/Init", true))()
end)

local Misc = Window:NewTab("Misc")
local MiscSection = Misc:NewSection("Misc")

MiscSection:NewButton("Dex Explorer V4", "Roblox server file browser", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Dex%20Explorer.txt"))()
end)
MiscSection:NewButton("BTools", "Give you the old builder tools", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/BTools.txt"))()
end)
MiscSection:NewButton("Dex Explorer V4", "Roblox server file browser", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Dex%20Explorer.txt"))()
end)
MiscSection:NewButton("Infinity Yield", "Gives you an Admin Console :)", function()
    loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Infinite%20Yield.txt"))()
end)
